RS + AB | #124 | Update deploy script for Digital Ocean

diff --git a/init-script/objective8d b/init-script/objective8d
--- a/init-script/objective8d
+++ b/init-script/objective8d
@@ -7,94 +7,98 @@ VERSION=0.0.1-SNAPSHOT
 PID_DIR=/var/run
 PID_FILE=$PID_DIR/$NAME.pid
 INSTALL_DIR=/usr/local/objective8
-INSTALL_JAR=$INSTALL_DIR/"$NAME"-"$VERSION"-standalone.jar
+JAR_NAME="$NAME"-"$VERSION"-standalone.jar
 mkdir -p $PID_DIR
 
-[ -f /etc/default/objective8_config ] && . /etc/default/objective8_config
+CONFIG_DIR=/etc/default/objective8_config 
+
+set -a
+. $CONFIG_DIR || echo "ERROR: Environment variables not set. Config file not found at $CONFIG_DIR"
 
 # returns 0 if PID in file is running, 1 if otherwise
 process_running() {
-	pid=`cat "$PID_FILE" 2>/dev/null`
-	if [ "$pid" = '' ]
-	then
-        	return 1 # PID file does not exist
-	else
-        	kill_report=`kill -0 $pid 2>&1`
-		if [ "$kill_report" = '' ]
-		then
-	    		return 0
-		else
-			echo "Stale PID file exists at $PID_FILE"
-			return 1
-		fi
-	fi
+  pid=`cat "$PID_FILE" 2>/dev/null`
+  if [ "$pid" = '' ]
+  then
+    return 1 # PID file does not exist
+  else
+    kill_report=`kill -0 $pid 2>&1`
+    if [ "$kill_report" = '' ]
+    then
+      return 0
+    else
+      echo "Stale PID file exists at $PID_FILE"
+      return 1
+    fi
+  fi
 }
 
 start() {
-	if process_running
-	then
-		echo "$NAME is already running as process `cat $PID_FILE`."
-		exit 1
-	fi
-	echo "Starting $NAME"
-	java -Dlog4j.configuration=log4j.debug -server -Xms256M -Xmx512M -XX:MaxPermSize=128M -jar $INSTALL_JAR &> /var/log/objective8d-init.log &
-	PID=$!
-	echo $PID > $PID_FILE
-	exit 0
+  if process_running
+  then
+    echo "$NAME is already running as process `cat $PID_FILE`."
+    exit 1
+  fi
+  echo "Starting $NAME"
+  cd $INSTALL_DIR
+  java -Dlog4j.configuration=log4j.debug -server -Xms256M -Xmx512M -XX:MaxPermSize=128M -jar $JAR_NAME &> /var/log/objective8d-init.log &
+  PID=$!
+  echo $PID > $PID_FILE
+  exit 0
 }	
 
 stop() {
-	if ! process_running
-	then
-		echo "$NAME is not running."
-	else
-		echo "Shutting down $NAME"
-		kill `cat $PID_FILE`
-		rm $PID_FILE
-	fi
+  if ! process_running
+  then
+    echo "$NAME is not running."
+  else
+    echo "Shutting down $NAME"
+    kill `cat $PID_FILE`
+    rm $PID_FILE
+  fi
 }
 
 force-stop() {
-	if ! process_running
-	then
-		echo "$NAME is not running."
-	else
-		echo "Forcefully shutting down $NAME"
-		kill -9 `cat $PID_FILE`
-		rm $PID_FILE
-	fi
+if ! process_running
+then
+  echo "$NAME is not running."
+else
+  echo "Forcefully shutting down $NAME"
+  kill -9 `cat $PID_FILE`
+  rm $PID_FILE
+fi
 }
 
 status() {
-	if process_running
-	then
-		echo "$NAME is running."
-	else
-		echo "$NAME is not running."
-	fi
-	exit 0
+  if process_running
+  then
+    echo "$NAME is running."
+  else
+    echo "$NAME is not running."
+  fi
+  exit 0
 }
 
 case "$1" in
-    start)
-	start
-	;;
-    stop)
-	stop
-	;;
-    force-stop)
-	force-stop
-	;;
-    status)
-	status
-	;;
-    restart)
+  start)
+    start
+    ;;
+  stop)
     stop
-	start
-	;;
-    *)
-        echo "Usage: "$NAME"d {start|stop|status|restart|force-stop}"
-	exit 1
-	;;
+    ;;
+  force-stop)
+    force-stop
+    ;;
+  status)
+    status
+    ;;
+  restart)
+    stop
+    start
+    ;;
+  *)
+    echo "Usage: "$NAME"d {start|stop|status|restart|force-stop}"
+    exit 1
+    ;;
 esac
 exit $?
